library(xtable)
library(igraph)
library(dplyr)
library(class)   # for knn
library(tidyr)
library(ggplot2)  # for plotting success rates
library(MASS)

#Lazy classifiers assume that everybody passes. Here we calculate their success rate
lazyPass<-as.numeric(table(centPS[[1]]$pass)[2]/sum(table(centPS[[1]]$pass))) #p=0.77
lazyJustPass<-as.numeric(table(centPS[[1]]$justpass)[2]/sum(table(centPS[[1]]$justpass))) #p=0.58

#Classifiers that only rely on background variables
load("data/centrality_data_frames.Rdata")
load("data/ROC_logreg.Rdata")

source("code/AUC_OnlyBackground_fci_c.R")
logRegP<-c(GCF_AUC_log,GF_AUC_log,GC_AUC_log,CF_AUC_log,F_AUC_log,G_AUC_log,C_AUC_log)
ldaP<-c(GCF_AUC_lda,GF_AUC_lda,GC_AUC_lda,CF_AUC_lda,F_AUC_lda,G_AUC_lda,C_AUC_lda)
qdaP<-c(GCF_AUC_qda,GF_AUC_qda,GC_AUC_qda,CF_AUC_qda,F_AUC_qda,G_AUC_qda,C_AUC_qda)
KNNP<-c(max(GCF_SR_knn),max(GF_SR_knn),max(GC_SR_knn),max(CF_SR_knn),max(F_SR_knn),max(G_SR_knn),max(C_SR_knn))
OnlyBackground<-data.frame(logistic=logRegP, LDA=ldaP,QDA=qdaP,KNN=KNNP)
rownames(OnlyBackground)<-c("GCF","GF","GC","CF","F","G","C")

xtable(OnlyBackground)

logRegP<-c(GCF_AUC_justpass_log,GF_AUC_justpass_log,GC_AUC_justpass_log,CF_AUC_justpass_log,F_AUC_justpass_log,G_AUC_justpass_log,C_AUC_justpass_log)
ldaP<-c(GCF_AUC_justpass_lda,GF_AUC_justpass_lda,GC_AUC_justpass_lda,CF_AUC_justpass_lda,F_AUC_justpass_lda,G_AUC_justpass_lda,C_AUC_justpass_lda)
qdaP<-c(GCF_AUC_justpass_qda,GF_AUC_justpass_qda,GC_AUC_justpass_qda,CF_AUC_justpass_qda,F_AUC_justpass_qda,G_AUC_justpass_qda,C_AUC_justpass_qda)
KNNP<-c(max(GCF_SR_knn_JP),max(GF_SR_knn_JP),max(GC_SR_knn_JP),max(CF_SR_knn_JP),max(F_SR_knn_JP),max(G_SR_knn_JP),max(C_SR_knn_JP))
OnlyBackground_JP<-data.frame(logistic=logRegP, LDA=ldaP,QDA=qdaP,KNN=KNNP)
rownames(OnlyBackground_JP)<-c("GCF","GF","GC","CF","F","G","C")

xtable(OnlyBackground_JP)

xtable(OnlyBackground_fci_pre_c)
xtable(OnlyBackground_JP_fci_pre_c)

###PLOTS NO BACKGROUND#####
plot(PS_AUC_NB_log_all, ylab="AUC", xlab="week", ylim=c(0,1),
     main="Logistic Regression Only Network Measures",type="o")
abline(h=(table(centPS[[1]]$pass)/sum(table(centPS[[1]]$pass)))[[2]])
lines(CD_AUC_NB_log_all,type="o",pch=2)
lines(ICS_AUC_NB_log_all,type="o",pch=3)
lines(PS_AUC_NB_log_PRTE,type="o",pch=4)
lines(CD_AUC_NB_log_PRTE,type="o",pch=5)
lines(ICS_AUC_NB_log_PRTE,type="o",pch=6)
lines(PS_AUC_NB_log_PRH,type="o",pch=7)
lines(CD_AUC_NB_log_PRH,type="o",pch=8)
lines(ICS_AUC_NB_log_PRH,type="o",pch=9)
lines(PS_AUC_NB_log_TEH,type="o",pch=10)
lines(CD_AUC_NB_log_TEH,type="o",pch=11)
lines(ICS_AUC_NB_log_TEH,type="o",pch=12)
lines(PS_AUC_NB_log_PR,type="o",pch=13)
lines(CD_AUC_NB_log_PR,type="o",pch=14)
lines(ICS_AUC_NB_log_PR,type="o",pch=15)
lines(PS_AUC_NB_log_TE,type="o",pch=16)
lines(CD_AUC_NB_log_TE,type="o",pch=17)
lines(ICS_AUC_NB_log_TE,type="o",pch=18)
lines(PS_AUC_NB_log_H,type="o",pch=19)
lines(CD_AUC_NB_log_H,type="o",pch=20)
lines(ICS_AUC_NB_log_H,type="o",pch=21)

plot(PS_AUC_NB_lda_all, ylab="AUC", xlab="week", ylim=c(0,1),
     main="LDA Only Network Measures",type="o")
abline(h=(table(centPS[[1]]$pass)/sum(table(centPS[[1]]$pass)))[[2]])
lines(CD_AUC_NB_lda_all,type="o",pch=2)
lines(ICS_AUC_NB_lda_all,type="o",pch=3)
lines(PS_AUC_NB_lda_PRTE,type="o",pch=4)
lines(CD_AUC_NB_lda_PRTE,type="o",pch=5)
lines(ICS_AUC_NB_lda_PRTE,type="o",pch=6)
lines(PS_AUC_NB_lda_PRH,type="o",pch=7)
lines(CD_AUC_NB_lda_PRH,type="o",pch=8)
lines(ICS_AUC_NB_lda_PRH,type="o",pch=9)
lines(PS_AUC_NB_lda_TEH,type="o",pch=10)
lines(CD_AUC_NB_lda_TEH,type="o",pch=11)
lines(ICS_AUC_NB_lda_TEH,type="o",pch=12)
lines(PS_AUC_NB_lda_PR,type="o",pch=13)
lines(CD_AUC_NB_lda_PR,type="o",pch=14)
lines(ICS_AUC_NB_lda_PR,type="o",pch=15)
lines(PS_AUC_NB_lda_TE,type="o",pch=16)
lines(CD_AUC_NB_lda_TE,type="o",pch=17)
lines(ICS_AUC_NB_lda_TE,type="o",pch=18)
lines(PS_AUC_NB_lda_H,type="o",pch=19)
lines(CD_AUC_NB_lda_H,type="o",pch=20)
lines(ICS_AUC_NB_lda_H,type="o",pch=21)

plot(PS_AUC_NB_qda_all, ylab="AUC", xlab="week", ylim=c(0,1),
     main="QDA Only Network Measures",type="o")
abline(h=(table(centPS[[1]]$pass)/sum(table(centPS[[1]]$pass)))[[2]])
lines(CD_AUC_NB_qda_all,type="o",pch=2)
lines(ICS_AUC_NB_qda_all,type="o",pch=3)
lines(PS_AUC_NB_qda_PRTE,type="o",pch=4)
lines(CD_AUC_NB_qda_PRTE,type="o",pch=5)
lines(ICS_AUC_NB_qda_PRTE,type="o",pch=6)
lines(PS_AUC_NB_qda_PRH,type="o",pch=7)
lines(CD_AUC_NB_qda_PRH,type="o",pch=8)
lines(ICS_AUC_NB_qda_PRH,type="o",pch=9)
lines(PS_AUC_NB_qda_TEH,type="o",pch=10)
lines(CD_AUC_NB_qda_TEH,type="o",pch=11)
lines(ICS_AUC_NB_qda_TEH,type="o",pch=12)
lines(PS_AUC_NB_qda_PR,type="o",pch=13)
lines(CD_AUC_NB_qda_PR,type="o",pch=14)
lines(ICS_AUC_NB_qda_PR,type="o",pch=15)
lines(PS_AUC_NB_qda_TE,type="o",pch=16)
lines(CD_AUC_NB_qda_TE,type="o",pch=17)
lines(ICS_AUC_NB_qda_TE,type="o",pch=18)
lines(PS_AUC_NB_qda_H,type="o",pch=19)
lines(CD_AUC_NB_qda_H,type="o",pch=20)
lines(ICS_AUC_NB_qda_H,type="o",pch=21)

plot(PS_mSR_NB_knn_all, ylab="mean SR over k=1 to k=20", xlab="week", ylim=c(0,1),
     main="KNN Only Network Measures",type="o")
abline(h=(table(centPS[[1]]$pass)/sum(table(centPS[[1]]$pass)))[[2]])
lines(CD_mSR_NB_knn_all,type="o",pch=2)
lines(ICS_mSR_NB_knn_all,type="o",pch=3)
lines(PS_mSR_NB_knn_PRTE,type="o",pch=4)
lines(CD_mSR_NB_knn_PRTE,type="o",pch=5)
lines(ICS_mSR_NB_knn_PRTE,type="o",pch=6)
lines(PS_mSR_NB_knn_PRH,type="o",pch=7)
lines(CD_mSR_NB_knn_PRH,type="o",pch=8)
lines(ICS_mSR_NB_knn_PRH,type="o",pch=9)
lines(PS_mSR_NB_knn_TEH,type="o",pch=10)
lines(CD_mSR_NB_knn_TEH,type="o",pch=11)
lines(ICS_mSR_NB_knn_TEH,type="o",pch=12)
lines(PS_mSR_NB_knn_PR,type="o",pch=13)
lines(CD_mSR_NB_knn_PR,type="o",pch=14)
lines(ICS_mSR_NB_knn_PR,type="o",pch=15)
lines(PS_mSR_NB_knn_TE,type="o",pch=16)
lines(CD_mSR_NB_knn_TE,type="o",pch=17)
lines(ICS_mSR_NB_knn_TE,type="o",pch=18)
lines(PS_mSR_NB_knn_H,type="o",pch=19)
lines(CD_mSR_NB_knn_H,type="o",pch=20)
lines(ICS_mSR_NB_knn_H,type="o",pch=21)


###PLOTS NO BACKGROUND JUST PASSED#####
plot(PS_AUC_NB_justpass_log_all, ylab="AUC", xlab="week", ylim=c(0,1),
     main="Logistic Regression Only Network Measures Just Passed",type="o")
abline(h=(table(centPS[[1]]$justpass)/sum(table(centPS[[1]]$justpass)))[[2]])
lines(CD_AUC_NB_justpass_log_all,type="o",pch=2)
lines(ICS_AUC_NB_justpass_log_all,type="o",pch=3)
lines(PS_AUC_NB_justpass_log_PRTE,type="o",pch=4)
lines(CD_AUC_NB_justpass_log_PRTE,type="o",pch=5)
lines(ICS_AUC_NB_justpass_log_PRTE,type="o",pch=6)
lines(PS_AUC_NB_justpass_log_PRH,type="o",pch=7)
lines(CD_AUC_NB_justpass_log_PRH,type="o",pch=8)
lines(ICS_AUC_NB_justpass_log_PRH,type="o",pch=9)
lines(PS_AUC_NB_justpass_log_TEH,type="o",pch=10)
lines(CD_AUC_NB_justpass_log_TEH,type="o",pch=11)
lines(ICS_AUC_NB_justpass_log_TEH,type="o",pch=12)
lines(PS_AUC_NB_justpass_log_PR,type="o",pch=13)
lines(CD_AUC_NB_justpass_log_PR,type="o",pch=14)
lines(ICS_AUC_NB_justpass_log_PR,type="o",pch=15)
lines(PS_AUC_NB_justpass_log_TE,type="o",pch=16)
lines(CD_AUC_NB_justpass_log_TE,type="o",pch=17)
lines(ICS_AUC_NB_justpass_log_TE,type="o",pch=18)
lines(PS_AUC_NB_justpass_log_H,type="o",pch=19)
lines(CD_AUC_NB_justpass_log_H,type="o",pch=20)
lines(ICS_AUC_NB_justpass_log_H,type="o",pch=21)

plot(PS_AUC_NB_justpass_lda_all, ylab="AUC", xlab="week", ylim=c(0,1),
     main="LDA Only Network Measures Just Passed",type="o")
abline(h=(table(centPS[[1]]$justpass)/sum(table(centPS[[1]]$justpass)))[[2]])
lines(CD_AUC_NB_justpass_lda_all,type="o",pch=2)
lines(ICS_AUC_NB_justpass_lda_all,type="o",pch=3)
lines(PS_AUC_NB_justpass_lda_PRTE,type="o",pch=4)
lines(CD_AUC_NB_justpass_lda_PRTE,type="o",pch=5)
lines(ICS_AUC_NB_justpass_lda_PRTE,type="o",pch=6)
lines(PS_AUC_NB_justpass_lda_PRH,type="o",pch=7)
lines(CD_AUC_NB_justpass_lda_PRH,type="o",pch=8)
lines(ICS_AUC_NB_justpass_lda_PRH,type="o",pch=9)
lines(PS_AUC_NB_justpass_lda_TEH,type="o",pch=10)
lines(CD_AUC_NB_justpass_lda_TEH,type="o",pch=11)
lines(ICS_AUC_NB_justpass_lda_TEH,type="o",pch=12)
lines(PS_AUC_NB_justpass_lda_PR,type="o",pch=13)
lines(CD_AUC_NB_justpass_lda_PR,type="o",pch=14)
lines(ICS_AUC_NB_justpass_lda_PR,type="o",pch=15)
lines(PS_AUC_NB_justpass_lda_TE,type="o",pch=16)
lines(CD_AUC_NB_justpass_lda_TE,type="o",pch=17)
lines(ICS_AUC_NB_justpass_lda_TE,type="o",pch=18)
lines(PS_AUC_NB_justpass_lda_H,type="o",pch=19)
lines(CD_AUC_NB_justpass_lda_H,type="o",pch=20)
lines(ICS_AUC_NB_justpass_lda_H,type="o",pch=21)

plot(PS_AUC_NB_justpass_qda_all, ylab="AUC", xlab="week", ylim=c(0,1),
     main="QDA Only Network Measures Just Passed",type="o")
abline(h=(table(centPS[[1]]$justpass)/sum(table(centPS[[1]]$justpass)))[[2]])
lines(CD_AUC_NB_justpass_qda_all,type="o",pch=2)
lines(ICS_AUC_NB_justpass_qda_all,type="o",pch=3)
lines(PS_AUC_NB_justpass_qda_PRTE,type="o",pch=4)
lines(CD_AUC_NB_justpass_qda_PRTE,type="o",pch=5)
lines(ICS_AUC_NB_justpass_qda_PRTE,type="o",pch=6)
lines(PS_AUC_NB_justpass_qda_PRH,type="o",pch=7)
lines(CD_AUC_NB_justpass_qda_PRH,type="o",pch=8)
lines(ICS_AUC_NB_justpass_qda_PRH,type="o",pch=9)
lines(PS_AUC_NB_justpass_qda_TEH,type="o",pch=10)
lines(CD_AUC_NB_justpass_qda_TEH,type="o",pch=11)
lines(ICS_AUC_NB_justpass_qda_TEH,type="o",pch=12)
lines(PS_AUC_NB_justpass_qda_PR,type="o",pch=13)
lines(CD_AUC_NB_justpass_qda_PR,type="o",pch=14)
lines(ICS_AUC_NB_justpass_qda_PR,type="o",pch=15)
lines(PS_AUC_NB_justpass_qda_TE,type="o",pch=16)
lines(CD_AUC_NB_justpass_qda_TE,type="o",pch=17)
lines(ICS_AUC_NB_justpass_qda_TE,type="o",pch=18)
lines(PS_AUC_NB_justpass_qda_H,type="o",pch=19)
lines(CD_AUC_NB_justpass_qda_H,type="o",pch=20)
lines(ICS_AUC_NB_justpass_qda_H,type="o",pch=21)

plot(PS_mSR_NB_justpass_knn_all, ylab ="mean SR over k=1 to k=20", xlab="week", ylim=c(0,1),
     main="KNN Only Network Measures Just Passed",type="o")
abline(h=(table(centPS[[1]]$justpass)/sum(table(centPS[[1]]$justpass)))[[2]])
lines(CD_mSR_NB_justpass_knn_all,type="o",pch=2)
lines(ICS_mSR_NB_justpass_knn_all,type="o",pch=3)
lines(PS_mSR_NB_justpass_knn_PRTE,type="o",pch=4)
lines(CD_mSR_NB_justpass_knn_PRTE,type="o",pch=5)
lines(ICS_mSR_NB_justpass_knn_PRTE,type="o",pch=6)
lines(PS_mSR_NB_justpass_knn_PRH,type="o",pch=7)
lines(CD_mSR_NB_justpass_knn_PRH,type="o",pch=8)
lines(ICS_mSR_NB_justpass_knn_PRH,type="o",pch=9)
lines(PS_mSR_NB_justpass_knn_TEH,type="o",pch=10)
lines(CD_mSR_NB_justpass_knn_TEH,type="o",pch=11)
lines(ICS_mSR_NB_justpass_knn_TEH,type="o",pch=12)
lines(PS_mSR_NB_justpass_knn_PR,type="o",pch=13)
lines(CD_mSR_NB_justpass_knn_PR,type="o",pch=14)
lines(ICS_mSR_NB_justpass_knn_PR,type="o",pch=15)
lines(PS_mSR_NB_justpass_knn_TE,type="o",pch=16)
lines(CD_mSR_NB_justpass_knn_TE,type="o",pch=17)
lines(ICS_mSR_NB_justpass_knn_TE,type="o",pch=18)
lines(PS_mSR_NB_justpass_knn_H,type="o",pch=19)
lines(CD_mSR_NB_justpass_knn_H,type="o",pch=20)
lines(ICS_mSR_NB_justpass_knn_H,type="o",pch=21)

#WITH FCI_C PRE

plot(PS_AUC_NetworkMeasuresFCI_C_log_all, ylab="AUC", xlab="week", ylim=c(0,1),
     main="Logistic Regression Network Measures and FCI_C pr",type="o")
abline(h=(table(centPS[[1]]$pass)/sum(table(centPS[[1]]$pass)))[[2]])
lines(CD_AUC_NetworkMeasuresFCI_C_log_all,type="o",pch=2)
lines(ICS_AUC_NetworkMeasuresFCI_C_log_all,type="o",pch=3)
lines(PS_AUC_NetworkMeasuresFCI_C_log_PRTE,type="o",pch=4)
lines(CD_AUC_NetworkMeasuresFCI_C_log_PRTE,type="o",pch=5)
lines(ICS_AUC_NetworkMeasuresFCI_C_log_PRTE,type="o",pch=6)
lines(PS_AUC_NetworkMeasuresFCI_C_log_PRH,type="o",pch=7)
lines(CD_AUC_NetworkMeasuresFCI_C_log_PRH,type="o",pch=8)
lines(ICS_AUC_NetworkMeasuresFCI_C_log_PRH,type="o",pch=9)
lines(PS_AUC_NetworkMeasuresFCI_C_log_TEH,type="o",pch=10)
lines(CD_AUC_NetworkMeasuresFCI_C_log_TEH,type="o",pch=11)
lines(ICS_AUC_NetworkMeasuresFCI_C_log_TEH,type="o",pch=12)
lines(PS_AUC_NetworkMeasuresFCI_C_log_PR,type="o",pch=13)
lines(CD_AUC_NetworkMeasuresFCI_C_log_PR,type="o",pch=14)
lines(ICS_AUC_NetworkMeasuresFCI_C_log_PR,type="o",pch=15)
lines(PS_AUC_NetworkMeasuresFCI_C_log_TE,type="o",pch=16)
lines(CD_AUC_NetworkMeasuresFCI_C_log_TE,type="o",pch=17)
lines(ICS_AUC_NetworkMeasuresFCI_C_log_TE,type="o",pch=18)
lines(PS_AUC_NetworkMeasuresFCI_C_log_H,type="o",pch=19)
lines(CD_AUC_NetworkMeasuresFCI_C_log_H,type="o",pch=20)
lines(ICS_AUC_NetworkMeasuresFCI_C_log_H,type="o",pch=21)

plot(PS_AUC_NetworkMeasuresFCI_C_justpass_log_all, ylab="AUC", xlab="week", ylim=c(0,1),
     main="Logistic Regression Network Measures and FCI_C pre",type="o")
abline(h=(table(centPS[[1]]$justpass)/sum(table(centPS[[1]]$justpass)))[[2]])
lines(CD_AUC_NetworkMeasuresFCI_C_justpass_log_all,type="o",pch=2)
lines(ICS_AUC_NetworkMeasuresFCI_C_justpass_log_all,type="o",pch=3)
lines(PS_AUC_NetworkMeasuresFCI_C_justpass_log_PRTE,type="o",pch=4)
lines(CD_AUC_NetworkMeasuresFCI_C_justpass_log_PRTE,type="o",pch=5)
lines(ICS_AUC_NetworkMeasuresFCI_C_justpass_log_PRTE,type="o",pch=6)
lines(PS_AUC_NetworkMeasuresFCI_C_justpass_log_PRH,type="o",pch=7)
lines(CD_AUC_NetworkMeasuresFCI_C_justpass_log_PRH,type="o",pch=8)
lines(ICS_AUC_NetworkMeasuresFCI_C_justpass_log_PRH,type="o",pch=9)
lines(PS_AUC_NetworkMeasuresFCI_C_justpass_log_TEH,type="o",pch=10)
lines(CD_AUC_NetworkMeasuresFCI_C_justpass_log_TEH,type="o",pch=11)
lines(ICS_AUC_NetworkMeasuresFCI_C_justpass_log_TEH,type="o",pch=12)
lines(PS_AUC_NetworkMeasuresFCI_C_justpass_log_PR,type="o",pch=13)
lines(CD_AUC_NetworkMeasuresFCI_C_justpass_log_PR,type="o",pch=14)
lines(ICS_AUC_NetworkMeasuresFCI_C_justpass_log_PR,type="o",pch=15)
lines(PS_AUC_NetworkMeasuresFCI_C_justpass_log_TE,type="o",pch=16)
lines(CD_AUC_NetworkMeasuresFCI_C_justpass_log_TE,type="o",pch=17)
lines(ICS_AUC_NetworkMeasuresFCI_C_justpass_log_TE,type="o",pch=18)
lines(PS_AUC_NetworkMeasuresFCI_C_justpass_log_H,type="o",pch=19)
lines(CD_AUC_NetworkMeasuresFCI_C_justpass_log_H,type="o",pch=20)
lines(ICS_AUC_NetworkMeasuresFCI_C_justpass_log_H,type="o",pch=21)

